### ISSUE TITLE
Edit footer

### ISSUE THREAD

**Issue by peerchemist** [virtualeconomy/docs#4]
![image](https://user-images.githubusercontent.com/7818961/151009812-504a504d-12cf-4a68-b0b8-ddf4e759227f.png)

This right part of the footer should be edited to include relevant links. Like, website, discord channel, telegram channel, github link, blockexplorer maybe?

**Comment by UnionX21** [comment]
vsys is a fake public chain,scammed three years.
no ecosystems
no community
no development plans and management.
no products
as a clown ,deformity public chain development team.
